import Head from "next/head";
import { Button, Container, Text, Title } from "@mantine/core";

export default function Home() {
  return (
    <>
      <Head>
        <title>next nest shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Container size={"800"}>
        <Title>
          NextJs NestJs{" "}
          <Text fw={500} component={"span"}>
            Shop
          </Text>
        </Title>
        <Button>Mantine button component</Button>
      </Container>
    </>
  );
}
